import { db } from '@/db';
import { dailyMetrics } from '@/db/schema';

async function main() {
    const today = new Date();
    
    // Helper function to get date N days ago
    const getDaysAgo = (days: number): Date => {
        const date = new Date(today);
        date.setDate(date.getDate() - days);
        return date;
    };

    // Helper function to format date as YYYY-MM-DD
    const formatDate = (date: Date): string => {
        return date.toISOString().split('T')[0];
    };

    const sampleMetrics = [
        // Kitchen 1 (Dapur Central Jakarta - HIGH PERFORMER)
        {
            dapurId: 1,
            date: formatDate(getDaysAgo(6)),
            portionTarget: 480,
            portionActual: 495,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14200,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(6).toISOString(),
        },
        {
            dapurId: 1,
            date: formatDate(getDaysAgo(5)),
            portionTarget: 480,
            portionActual: 490,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14100,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(5).toISOString(),
        },
        {
            dapurId: 1,
            date: formatDate(getDaysAgo(4)),
            portionTarget: 480,
            portionActual: 498,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14300,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(4).toISOString(),
        },
        {
            dapurId: 1,
            date: formatDate(getDaysAgo(3)),
            portionTarget: 480,
            portionActual: 502,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14000,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(3).toISOString(),
        },
        {
            dapurId: 1,
            date: formatDate(getDaysAgo(2)),
            portionTarget: 480,
            portionActual: 492,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14250,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(2).toISOString(),
        },
        {
            dapurId: 1,
            date: formatDate(getDaysAgo(1)),
            portionTarget: 480,
            portionActual: 488,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14150,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(1).toISOString(),
        },
        {
            dapurId: 1,
            date: formatDate(getDaysAgo(0)),
            portionTarget: 480,
            portionActual: 505,
            budgetPerPortion: 15000,
            actualCostPerPortion: 13900,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(0).toISOString(),
        },

        // Kitchen 2 (Dapur South Jakarta - GOOD PERFORMER)
        {
            dapurId: 2,
            date: formatDate(getDaysAgo(6)),
            portionTarget: 430,
            portionActual: 428,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14900,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(6).toISOString(),
        },
        {
            dapurId: 2,
            date: formatDate(getDaysAgo(5)),
            portionTarget: 430,
            portionActual: 432,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15100,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(5).toISOString(),
        },
        {
            dapurId: 2,
            date: formatDate(getDaysAgo(4)),
            portionTarget: 430,
            portionActual: 430,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15000,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(4).toISOString(),
        },
        {
            dapurId: 2,
            date: formatDate(getDaysAgo(3)),
            portionTarget: 430,
            portionActual: 435,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14800,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(3).toISOString(),
        },
        {
            dapurId: 2,
            date: formatDate(getDaysAgo(2)),
            portionTarget: 430,
            portionActual: 427,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15200,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(2).toISOString(),
        },
        {
            dapurId: 2,
            date: formatDate(getDaysAgo(1)),
            portionTarget: 430,
            portionActual: 433,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14950,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(1).toISOString(),
        },
        {
            dapurId: 2,
            date: formatDate(getDaysAgo(0)),
            portionTarget: 430,
            portionActual: 431,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15050,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(0).toISOString(),
        },

        // Kitchen 3 (Dapur West Jakarta - AVERAGE)
        {
            dapurId: 3,
            date: formatDate(getDaysAgo(6)),
            portionTarget: 380,
            portionActual: 365,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15400,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(6).toISOString(),
        },
        {
            dapurId: 3,
            date: formatDate(getDaysAgo(5)),
            portionTarget: 380,
            portionActual: 372,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15600,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(5).toISOString(),
        },
        {
            dapurId: 3,
            date: formatDate(getDaysAgo(4)),
            portionTarget: 380,
            portionActual: 388,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15200,
            kitchenStatus: 'Overload',
            createdAt: getDaysAgo(4).toISOString(),
        },
        {
            dapurId: 3,
            date: formatDate(getDaysAgo(3)),
            portionTarget: 380,
            portionActual: 375,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15500,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(3).toISOString(),
        },
        {
            dapurId: 3,
            date: formatDate(getDaysAgo(2)),
            portionTarget: 380,
            portionActual: 368,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15700,
            kitchenStatus: 'Gangguan',
            createdAt: getDaysAgo(2).toISOString(),
        },
        {
            dapurId: 3,
            date: formatDate(getDaysAgo(1)),
            portionTarget: 380,
            portionActual: 382,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15300,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(1).toISOString(),
        },
        {
            dapurId: 3,
            date: formatDate(getDaysAgo(0)),
            portionTarget: 380,
            portionActual: 370,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15650,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(0).toISOString(),
        },

        // Kitchen 4 (Dapur East Jakarta - NEEDS IMPROVEMENT)
        {
            dapurId: 4,
            date: formatDate(getDaysAgo(6)),
            portionTarget: 330,
            portionActual: 285,
            budgetPerPortion: 15000,
            actualCostPerPortion: 16500,
            kitchenStatus: 'Gangguan',
            createdAt: getDaysAgo(6).toISOString(),
        },
        {
            dapurId: 4,
            date: formatDate(getDaysAgo(5)),
            portionTarget: 330,
            portionActual: 292,
            budgetPerPortion: 15000,
            actualCostPerPortion: 16200,
            kitchenStatus: 'Gangguan',
            createdAt: getDaysAgo(5).toISOString(),
        },
        {
            dapurId: 4,
            date: formatDate(getDaysAgo(4)),
            portionTarget: 330,
            portionActual: 278,
            budgetPerPortion: 15000,
            actualCostPerPortion: 16800,
            kitchenStatus: 'Gangguan',
            createdAt: getDaysAgo(4).toISOString(),
        },
        {
            dapurId: 4,
            date: formatDate(getDaysAgo(3)),
            portionTarget: 330,
            portionActual: 295,
            budgetPerPortion: 15000,
            actualCostPerPortion: 16100,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(3).toISOString(),
        },
        {
            dapurId: 4,
            date: formatDate(getDaysAgo(2)),
            portionTarget: 330,
            portionActual: 302,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15900,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(2).toISOString(),
        },
        {
            dapurId: 4,
            date: formatDate(getDaysAgo(1)),
            portionTarget: 330,
            portionActual: 288,
            budgetPerPortion: 15000,
            actualCostPerPortion: 16400,
            kitchenStatus: 'Gangguan',
            createdAt: getDaysAgo(1).toISOString(),
        },
        {
            dapurId: 4,
            date: formatDate(getDaysAgo(0)),
            portionTarget: 330,
            portionActual: 296,
            budgetPerPortion: 15000,
            actualCostPerPortion: 16000,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(0).toISOString(),
        },

        // Kitchen 5 (Dapur North Jakarta - MIXED PERFORMANCE)
        {
            dapurId: 5,
            date: formatDate(getDaysAgo(6)),
            portionTarget: 360,
            portionActual: 345,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15600,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(6).toISOString(),
        },
        {
            dapurId: 5,
            date: formatDate(getDaysAgo(5)),
            portionTarget: 360,
            portionActual: 368,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14700,
            kitchenStatus: 'Overload',
            createdAt: getDaysAgo(5).toISOString(),
        },
        {
            dapurId: 5,
            date: formatDate(getDaysAgo(4)),
            portionTarget: 360,
            portionActual: 352,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15400,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(4).toISOString(),
        },
        {
            dapurId: 5,
            date: formatDate(getDaysAgo(3)),
            portionTarget: 360,
            portionActual: 372,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14500,
            kitchenStatus: 'Overload',
            createdAt: getDaysAgo(3).toISOString(),
        },
        {
            dapurId: 5,
            date: formatDate(getDaysAgo(2)),
            portionTarget: 360,
            portionActual: 340,
            budgetPerPortion: 15000,
            actualCostPerPortion: 16000,
            kitchenStatus: 'Gangguan',
            createdAt: getDaysAgo(2).toISOString(),
        },
        {
            dapurId: 5,
            date: formatDate(getDaysAgo(1)),
            portionTarget: 360,
            portionActual: 355,
            budgetPerPortion: 15000,
            actualCostPerPortion: 15300,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(1).toISOString(),
        },
        {
            dapurId: 5,
            date: formatDate(getDaysAgo(0)),
            portionTarget: 360,
            portionActual: 365,
            budgetPerPortion: 15000,
            actualCostPerPortion: 14900,
            kitchenStatus: 'Normal',
            createdAt: getDaysAgo(0).toISOString(),
        },
    ];

    await db.insert(dailyMetrics).values(sampleMetrics);
    
    console.log('✅ Daily metrics seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});