import { db } from '@/db';
import { sanitationScores } from '@/db/schema';

async function main() {
    const today = new Date();
    const dates = Array.from({ length: 7 }, (_, i) => {
        const date = new Date(today);
        date.setDate(date.getDate() - (6 - i));
        return date.toISOString().split('T')[0];
    });

    const sampleScores = [
        // Kitchen 1 - HIGH PERFORMER (88-95 scores)
        {
            dapurId: 1,
            date: dates[0],
            kitchenCleanliness: 92,
            storage: 90,
            equipment: 91,
            personalHygiene: 94,
            pestControl: 89,
            documentation: 93,
            createdAt: new Date(dates[0]).toISOString(),
        },
        {
            dapurId: 1,
            date: dates[1],
            kitchenCleanliness: 93,
            storage: 91,
            equipment: 92,
            personalHygiene: 95,
            pestControl: 90,
            documentation: 94,
            createdAt: new Date(dates[1]).toISOString(),
        },
        {
            dapurId: 1,
            date: dates[2],
            kitchenCleanliness: 91,
            storage: 89,
            equipment: 90,
            personalHygiene: 93,
            pestControl: 88,
            documentation: 92,
            createdAt: new Date(dates[2]).toISOString(),
        },
        {
            dapurId: 1,
            date: dates[3],
            kitchenCleanliness: 94,
            storage: 92,
            equipment: 93,
            personalHygiene: 95,
            pestControl: 91,
            documentation: 94,
            createdAt: new Date(dates[3]).toISOString(),
        },
        {
            dapurId: 1,
            date: dates[4],
            kitchenCleanliness: 92,
            storage: 90,
            equipment: 91,
            personalHygiene: 94,
            pestControl: 89,
            documentation: 93,
            createdAt: new Date(dates[4]).toISOString(),
        },
        {
            dapurId: 1,
            date: dates[5],
            kitchenCleanliness: 93,
            storage: 91,
            equipment: 92,
            personalHygiene: 95,
            pestControl: 90,
            documentation: 93,
            createdAt: new Date(dates[5]).toISOString(),
        },
        {
            dapurId: 1,
            date: dates[6],
            kitchenCleanliness: 95,
            storage: 93,
            equipment: 94,
            personalHygiene: 96,
            pestControl: 92,
            documentation: 95,
            createdAt: new Date(dates[6]).toISOString(),
        },

        // Kitchen 2 - GOOD PERFORMER (85-90 scores)
        {
            dapurId: 2,
            date: dates[0],
            kitchenCleanliness: 87,
            storage: 86,
            equipment: 88,
            personalHygiene: 89,
            pestControl: 85,
            documentation: 88,
            createdAt: new Date(dates[0]).toISOString(),
        },
        {
            dapurId: 2,
            date: dates[1],
            kitchenCleanliness: 88,
            storage: 87,
            equipment: 89,
            personalHygiene: 90,
            pestControl: 86,
            documentation: 89,
            createdAt: new Date(dates[1]).toISOString(),
        },
        {
            dapurId: 2,
            date: dates[2],
            kitchenCleanliness: 86,
            storage: 85,
            equipment: 87,
            personalHygiene: 88,
            pestControl: 84,
            documentation: 87,
            createdAt: new Date(dates[2]).toISOString(),
        },
        {
            dapurId: 2,
            date: dates[3],
            kitchenCleanliness: 89,
            storage: 88,
            equipment: 90,
            personalHygiene: 91,
            pestControl: 87,
            documentation: 90,
            createdAt: new Date(dates[3]).toISOString(),
        },
        {
            dapurId: 2,
            date: dates[4],
            kitchenCleanliness: 87,
            storage: 86,
            equipment: 88,
            personalHygiene: 89,
            pestControl: 85,
            documentation: 88,
            createdAt: new Date(dates[4]).toISOString(),
        },
        {
            dapurId: 2,
            date: dates[5],
            kitchenCleanliness: 88,
            storage: 87,
            equipment: 89,
            personalHygiene: 90,
            pestControl: 86,
            documentation: 89,
            createdAt: new Date(dates[5]).toISOString(),
        },
        {
            dapurId: 2,
            date: dates[6],
            kitchenCleanliness: 90,
            storage: 89,
            equipment: 91,
            personalHygiene: 92,
            pestControl: 88,
            documentation: 91,
            createdAt: new Date(dates[6]).toISOString(),
        },

        // Kitchen 3 - AVERAGE (78-85 scores)
        {
            dapurId: 3,
            date: dates[0],
            kitchenCleanliness: 80,
            storage: 78,
            equipment: 82,
            personalHygiene: 83,
            pestControl: 77,
            documentation: 81,
            createdAt: new Date(dates[0]).toISOString(),
        },
        {
            dapurId: 3,
            date: dates[1],
            kitchenCleanliness: 82,
            storage: 80,
            equipment: 83,
            personalHygiene: 84,
            pestControl: 79,
            documentation: 82,
            createdAt: new Date(dates[1]).toISOString(),
        },
        {
            dapurId: 3,
            date: dates[2],
            kitchenCleanliness: 81,
            storage: 79,
            equipment: 82,
            personalHygiene: 83,
            pestControl: 78,
            documentation: 81,
            createdAt: new Date(dates[2]).toISOString(),
        },
        {
            dapurId: 3,
            date: dates[3],
            kitchenCleanliness: 83,
            storage: 81,
            equipment: 84,
            personalHygiene: 85,
            pestControl: 80,
            documentation: 83,
            createdAt: new Date(dates[3]).toISOString(),
        },
        {
            dapurId: 3,
            date: dates[4],
            kitchenCleanliness: 79,
            storage: 77,
            equipment: 81,
            personalHygiene: 82,
            pestControl: 76,
            documentation: 80,
            createdAt: new Date(dates[4]).toISOString(),
        },
        {
            dapurId: 3,
            date: dates[5],
            kitchenCleanliness: 82,
            storage: 80,
            equipment: 83,
            personalHygiene: 84,
            pestControl: 79,
            documentation: 82,
            createdAt: new Date(dates[5]).toISOString(),
        },
        {
            dapurId: 3,
            date: dates[6],
            kitchenCleanliness: 84,
            storage: 82,
            equipment: 85,
            personalHygiene: 86,
            pestControl: 81,
            documentation: 84,
            createdAt: new Date(dates[6]).toISOString(),
        },

        // Kitchen 4 - NEEDS IMPROVEMENT (68-78 scores)
        {
            dapurId: 4,
            date: dates[0],
            kitchenCleanliness: 70,
            storage: 68,
            equipment: 72,
            personalHygiene: 73,
            pestControl: 67,
            documentation: 71,
            createdAt: new Date(dates[0]).toISOString(),
        },
        {
            dapurId: 4,
            date: dates[1],
            kitchenCleanliness: 72,
            storage: 70,
            equipment: 73,
            personalHygiene: 74,
            pestControl: 69,
            documentation: 72,
            createdAt: new Date(dates[1]).toISOString(),
        },
        {
            dapurId: 4,
            date: dates[2],
            kitchenCleanliness: 69,
            storage: 67,
            equipment: 71,
            personalHygiene: 72,
            pestControl: 66,
            documentation: 70,
            createdAt: new Date(dates[2]).toISOString(),
        },
        {
            dapurId: 4,
            date: dates[3],
            kitchenCleanliness: 73,
            storage: 71,
            equipment: 74,
            personalHygiene: 75,
            pestControl: 70,
            documentation: 73,
            createdAt: new Date(dates[3]).toISOString(),
        },
        {
            dapurId: 4,
            date: dates[4],
            kitchenCleanliness: 75,
            storage: 73,
            equipment: 76,
            personalHygiene: 77,
            pestControl: 72,
            documentation: 75,
            createdAt: new Date(dates[4]).toISOString(),
        },
        {
            dapurId: 4,
            date: dates[5],
            kitchenCleanliness: 71,
            storage: 69,
            equipment: 73,
            personalHygiene: 74,
            pestControl: 68,
            documentation: 72,
            createdAt: new Date(dates[5]).toISOString(),
        },
        {
            dapurId: 4,
            date: dates[6],
            kitchenCleanliness: 74,
            storage: 72,
            equipment: 75,
            personalHygiene: 76,
            pestControl: 71,
            documentation: 74,
            createdAt: new Date(dates[6]).toISOString(),
        },

        // Kitchen 5 - MIXED (75-88 scores, varying)
        {
            dapurId: 5,
            date: dates[0],
            kitchenCleanliness: 78,
            storage: 76,
            equipment: 80,
            personalHygiene: 81,
            pestControl: 75,
            documentation: 79,
            createdAt: new Date(dates[0]).toISOString(),
        },
        {
            dapurId: 5,
            date: dates[1],
            kitchenCleanliness: 85,
            storage: 83,
            equipment: 86,
            personalHygiene: 88,
            pestControl: 82,
            documentation: 86,
            createdAt: new Date(dates[1]).toISOString(),
        },
        {
            dapurId: 5,
            date: dates[2],
            kitchenCleanliness: 80,
            storage: 78,
            equipment: 82,
            personalHygiene: 83,
            pestControl: 77,
            documentation: 81,
            createdAt: new Date(dates[2]).toISOString(),
        },
        {
            dapurId: 5,
            date: dates[3],
            kitchenCleanliness: 87,
            storage: 85,
            equipment: 88,
            personalHygiene: 90,
            pestControl: 84,
            documentation: 88,
            createdAt: new Date(dates[3]).toISOString(),
        },
        {
            dapurId: 5,
            date: dates[4],
            kitchenCleanliness: 76,
            storage: 74,
            equipment: 78,
            personalHygiene: 79,
            pestControl: 73,
            documentation: 77,
            createdAt: new Date(dates[4]).toISOString(),
        },
        {
            dapurId: 5,
            date: dates[5],
            kitchenCleanliness: 82,
            storage: 80,
            equipment: 84,
            personalHygiene: 85,
            pestControl: 79,
            documentation: 83,
            createdAt: new Date(dates[5]).toISOString(),
        },
        {
            dapurId: 5,
            date: dates[6],
            kitchenCleanliness: 84,
            storage: 82,
            equipment: 86,
            personalHygiene: 87,
            pestControl: 81,
            documentation: 85,
            createdAt: new Date(dates[6]).toISOString(),
        },
    ];

    await db.insert(sanitationScores).values(sampleScores);
    
    console.log('✅ Sanitation scores seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});