import { db } from '@/db';
import { staffAttendance } from '@/db/schema';

async function main() {
    const today = new Date();
    const last7Days = Array.from({ length: 7 }, (_, i) => {
        const date = new Date(today);
        date.setDate(date.getDate() - (6 - i));
        return date.toISOString().split('T')[0];
    });

    const sampleAttendance = [
        // Kitchen 1 (HIGH PERFORMER - 95-98% attendance)
        {
            dapurId: 1,
            date: last7Days[0],
            totalStaff: 20,
            present: 19,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[0]).toISOString(),
        },
        {
            dapurId: 1,
            date: last7Days[1],
            totalStaff: 20,
            present: 20,
            onLeave: 0,
            sick: 0,
            createdAt: new Date(last7Days[1]).toISOString(),
        },
        {
            dapurId: 1,
            date: last7Days[2],
            totalStaff: 20,
            present: 19,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(last7Days[2]).toISOString(),
        },
        {
            dapurId: 1,
            date: last7Days[3],
            totalStaff: 20,
            present: 20,
            onLeave: 0,
            sick: 0,
            createdAt: new Date(last7Days[3]).toISOString(),
        },
        {
            dapurId: 1,
            date: last7Days[4],
            totalStaff: 20,
            present: 19,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[4]).toISOString(),
        },
        {
            dapurId: 1,
            date: last7Days[5],
            totalStaff: 20,
            present: 20,
            onLeave: 0,
            sick: 0,
            createdAt: new Date(last7Days[5]).toISOString(),
        },
        {
            dapurId: 1,
            date: last7Days[6],
            totalStaff: 20,
            present: 19,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(last7Days[6]).toISOString(),
        },

        // Kitchen 2 (GOOD PERFORMER - 90-95% attendance)
        {
            dapurId: 2,
            date: last7Days[0],
            totalStaff: 18,
            present: 17,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[0]).toISOString(),
        },
        {
            dapurId: 2,
            date: last7Days[1],
            totalStaff: 18,
            present: 17,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(last7Days[1]).toISOString(),
        },
        {
            dapurId: 2,
            date: last7Days[2],
            totalStaff: 18,
            present: 18,
            onLeave: 0,
            sick: 0,
            createdAt: new Date(last7Days[2]).toISOString(),
        },
        {
            dapurId: 2,
            date: last7Days[3],
            totalStaff: 18,
            present: 16,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(last7Days[3]).toISOString(),
        },
        {
            dapurId: 2,
            date: last7Days[4],
            totalStaff: 18,
            present: 17,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[4]).toISOString(),
        },
        {
            dapurId: 2,
            date: last7Days[5],
            totalStaff: 18,
            present: 17,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(last7Days[5]).toISOString(),
        },
        {
            dapurId: 2,
            date: last7Days[6],
            totalStaff: 18,
            present: 17,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[6]).toISOString(),
        },

        // Kitchen 3 (AVERAGE - 88-92% attendance)
        {
            dapurId: 3,
            date: last7Days[0],
            totalStaff: 16,
            present: 14,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(last7Days[0]).toISOString(),
        },
        {
            dapurId: 3,
            date: last7Days[1],
            totalStaff: 16,
            present: 15,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[1]).toISOString(),
        },
        {
            dapurId: 3,
            date: last7Days[2],
            totalStaff: 16,
            present: 14,
            onLeave: 0,
            sick: 2,
            createdAt: new Date(last7Days[2]).toISOString(),
        },
        {
            dapurId: 3,
            date: last7Days[3],
            totalStaff: 16,
            present: 15,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[3]).toISOString(),
        },
        {
            dapurId: 3,
            date: last7Days[4],
            totalStaff: 16,
            present: 14,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(last7Days[4]).toISOString(),
        },
        {
            dapurId: 3,
            date: last7Days[5],
            totalStaff: 16,
            present: 15,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(last7Days[5]).toISOString(),
        },
        {
            dapurId: 3,
            date: last7Days[6],
            totalStaff: 16,
            present: 14,
            onLeave: 2,
            sick: 0,
            createdAt: new Date(last7Days[6]).toISOString(),
        },

        // Kitchen 4 (NEEDS IMPROVEMENT - 80-88% attendance)
        {
            dapurId: 4,
            date: last7Days[0],
            totalStaff: 15,
            present: 12,
            onLeave: 2,
            sick: 1,
            createdAt: new Date(last7Days[0]).toISOString(),
        },
        {
            dapurId: 4,
            date: last7Days[1],
            totalStaff: 15,
            present: 13,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(last7Days[1]).toISOString(),
        },
        {
            dapurId: 4,
            date: last7Days[2],
            totalStaff: 15,
            present: 12,
            onLeave: 1,
            sick: 2,
            createdAt: new Date(last7Days[2]).toISOString(),
        },
        {
            dapurId: 4,
            date: last7Days[3],
            totalStaff: 15,
            present: 13,
            onLeave: 2,
            sick: 0,
            createdAt: new Date(last7Days[3]).toISOString(),
        },
        {
            dapurId: 4,
            date: last7Days[4],
            totalStaff: 15,
            present: 13,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(last7Days[4]).toISOString(),
        },
        {
            dapurId: 4,
            date: last7Days[5],
            totalStaff: 15,
            present: 12,
            onLeave: 2,
            sick: 1,
            createdAt: new Date(last7Days[5]).toISOString(),
        },
        {
            dapurId: 4,
            date: last7Days[6],
            totalStaff: 15,
            present: 13,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(last7Days[6]).toISOString(),
        },

        // Kitchen 5 (MIXED - 85-93% attendance)
        {
            dapurId: 5,
            date: last7Days[0],
            totalStaff: 17,
            present: 15,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(last7Days[0]).toISOString(),
        },
        {
            dapurId: 5,
            date: last7Days[1],
            totalStaff: 17,
            present: 16,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[1]).toISOString(),
        },
        {
            dapurId: 5,
            date: last7Days[2],
            totalStaff: 17,
            present: 15,
            onLeave: 0,
            sick: 2,
            createdAt: new Date(last7Days[2]).toISOString(),
        },
        {
            dapurId: 5,
            date: last7Days[3],
            totalStaff: 17,
            present: 16,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(last7Days[3]).toISOString(),
        },
        {
            dapurId: 5,
            date: last7Days[4],
            totalStaff: 17,
            present: 14,
            onLeave: 2,
            sick: 1,
            createdAt: new Date(last7Days[4]).toISOString(),
        },
        {
            dapurId: 5,
            date: last7Days[5],
            totalStaff: 17,
            present: 15,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(last7Days[5]).toISOString(),
        },
        {
            dapurId: 5,
            date: last7Days[6],
            totalStaff: 17,
            present: 16,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(last7Days[6]).toISOString(),
        },
    ];

    await db.insert(staffAttendance).values(sampleAttendance);
    
    console.log('✅ Staff attendance seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});