import { db } from '@/db';
import { staffAttendance } from '@/db/schema';

async function main() {
    const today = new Date();
    
    // Generate dates from 7 days ago to 1 day ago
    const generateDate = (daysAgo: number): string => {
        const date = new Date(today);
        date.setDate(date.getDate() - daysAgo);
        return date.toISOString().split('T')[0];
    };

    const sampleStaffAttendance = [
        // Kitchen 7 - HIGH PERFORMER (95-100% attendance)
        {
            dapurId: 7,
            date: generateDate(7),
            totalStaff: 20,
            present: 19,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(7)).toISOString(),
        },
        {
            dapurId: 7,
            date: generateDate(6),
            totalStaff: 20,
            present: 20,
            onLeave: 0,
            sick: 0,
            createdAt: new Date(generateDate(6)).toISOString(),
        },
        {
            dapurId: 7,
            date: generateDate(5),
            totalStaff: 20,
            present: 19,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(generateDate(5)).toISOString(),
        },
        {
            dapurId: 7,
            date: generateDate(4),
            totalStaff: 20,
            present: 20,
            onLeave: 0,
            sick: 0,
            createdAt: new Date(generateDate(4)).toISOString(),
        },
        {
            dapurId: 7,
            date: generateDate(3),
            totalStaff: 20,
            present: 19,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(3)).toISOString(),
        },
        {
            dapurId: 7,
            date: generateDate(2),
            totalStaff: 20,
            present: 20,
            onLeave: 0,
            sick: 0,
            createdAt: new Date(generateDate(2)).toISOString(),
        },
        {
            dapurId: 7,
            date: generateDate(1),
            totalStaff: 20,
            present: 19,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(generateDate(1)).toISOString(),
        },

        // Kitchen 8 - GOOD PERFORMER (90-95% attendance)
        {
            dapurId: 8,
            date: generateDate(7),
            totalStaff: 18,
            present: 17,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(7)).toISOString(),
        },
        {
            dapurId: 8,
            date: generateDate(6),
            totalStaff: 18,
            present: 17,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(generateDate(6)).toISOString(),
        },
        {
            dapurId: 8,
            date: generateDate(5),
            totalStaff: 18,
            present: 18,
            onLeave: 0,
            sick: 0,
            createdAt: new Date(generateDate(5)).toISOString(),
        },
        {
            dapurId: 8,
            date: generateDate(4),
            totalStaff: 18,
            present: 16,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(generateDate(4)).toISOString(),
        },
        {
            dapurId: 8,
            date: generateDate(3),
            totalStaff: 18,
            present: 17,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(3)).toISOString(),
        },
        {
            dapurId: 8,
            date: generateDate(2),
            totalStaff: 18,
            present: 17,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(generateDate(2)).toISOString(),
        },
        {
            dapurId: 8,
            date: generateDate(1),
            totalStaff: 18,
            present: 17,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(1)).toISOString(),
        },

        // Kitchen 9 - AVERAGE (88-92% attendance)
        {
            dapurId: 9,
            date: generateDate(7),
            totalStaff: 16,
            present: 14,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(generateDate(7)).toISOString(),
        },
        {
            dapurId: 9,
            date: generateDate(6),
            totalStaff: 16,
            present: 15,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(6)).toISOString(),
        },
        {
            dapurId: 9,
            date: generateDate(5),
            totalStaff: 16,
            present: 14,
            onLeave: 0,
            sick: 2,
            createdAt: new Date(generateDate(5)).toISOString(),
        },
        {
            dapurId: 9,
            date: generateDate(4),
            totalStaff: 16,
            present: 15,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(4)).toISOString(),
        },
        {
            dapurId: 9,
            date: generateDate(3),
            totalStaff: 16,
            present: 14,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(generateDate(3)).toISOString(),
        },
        {
            dapurId: 9,
            date: generateDate(2),
            totalStaff: 16,
            present: 15,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(generateDate(2)).toISOString(),
        },
        {
            dapurId: 9,
            date: generateDate(1),
            totalStaff: 16,
            present: 14,
            onLeave: 2,
            sick: 0,
            createdAt: new Date(generateDate(1)).toISOString(),
        },

        // Kitchen 10 - NEEDS IMPROVEMENT (80-88% attendance)
        {
            dapurId: 10,
            date: generateDate(7),
            totalStaff: 15,
            present: 12,
            onLeave: 2,
            sick: 1,
            createdAt: new Date(generateDate(7)).toISOString(),
        },
        {
            dapurId: 10,
            date: generateDate(6),
            totalStaff: 15,
            present: 13,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(generateDate(6)).toISOString(),
        },
        {
            dapurId: 10,
            date: generateDate(5),
            totalStaff: 15,
            present: 12,
            onLeave: 1,
            sick: 2,
            createdAt: new Date(generateDate(5)).toISOString(),
        },
        {
            dapurId: 10,
            date: generateDate(4),
            totalStaff: 15,
            present: 13,
            onLeave: 2,
            sick: 0,
            createdAt: new Date(generateDate(4)).toISOString(),
        },
        {
            dapurId: 10,
            date: generateDate(3),
            totalStaff: 15,
            present: 13,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(generateDate(3)).toISOString(),
        },
        {
            dapurId: 10,
            date: generateDate(2),
            totalStaff: 15,
            present: 12,
            onLeave: 2,
            sick: 1,
            createdAt: new Date(generateDate(2)).toISOString(),
        },
        {
            dapurId: 10,
            date: generateDate(1),
            totalStaff: 15,
            present: 13,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(generateDate(1)).toISOString(),
        },

        // Kitchen 11 - MIXED (85-93% attendance)
        {
            dapurId: 11,
            date: generateDate(7),
            totalStaff: 17,
            present: 15,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(generateDate(7)).toISOString(),
        },
        {
            dapurId: 11,
            date: generateDate(6),
            totalStaff: 17,
            present: 16,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(6)).toISOString(),
        },
        {
            dapurId: 11,
            date: generateDate(5),
            totalStaff: 17,
            present: 15,
            onLeave: 0,
            sick: 2,
            createdAt: new Date(generateDate(5)).toISOString(),
        },
        {
            dapurId: 11,
            date: generateDate(4),
            totalStaff: 17,
            present: 16,
            onLeave: 1,
            sick: 0,
            createdAt: new Date(generateDate(4)).toISOString(),
        },
        {
            dapurId: 11,
            date: generateDate(3),
            totalStaff: 17,
            present: 14,
            onLeave: 2,
            sick: 1,
            createdAt: new Date(generateDate(3)).toISOString(),
        },
        {
            dapurId: 11,
            date: generateDate(2),
            totalStaff: 17,
            present: 15,
            onLeave: 1,
            sick: 1,
            createdAt: new Date(generateDate(2)).toISOString(),
        },
        {
            dapurId: 11,
            date: generateDate(1),
            totalStaff: 17,
            present: 16,
            onLeave: 0,
            sick: 1,
            createdAt: new Date(generateDate(1)).toISOString(),
        },
    ];

    await db.insert(staffAttendance).values(sampleStaffAttendance);
    
    console.log('✅ Staff attendance seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});